package br.com.alepmendonca.creditcardusage.model;

import br.com.alepmendonca.creditcardusage.dao.DaoSession;
import de.greenrobot.dao.DaoException;

import br.com.alepmendonca.creditcardusage.dao.CardReceiptDao;
import br.com.alepmendonca.creditcardusage.dao.CreditCardDao;
import br.com.alepmendonca.creditcardusage.dao.StoreDao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.Comparator;
import java.util.Currency;
import java.util.Locale;
// KEEP INCLUDES END
/**
 * Entity mapped to table CARD_RECEIPT.
 */
public class CardReceipt {

    private Long id;
    private long creditCardId;
    private long storeId;
    private double value;
    /** Not-null value. */
    private String currency;
    private long transaction;
    /** Not-null value. */
    private java.util.Date authorizationDate;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient CardReceiptDao myDao;

    private CreditCard creditCard;
    private Long creditCard__resolvedKey;

    private Store store;
    private Long store__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CardReceipt() {
    }

    public CardReceipt(Long id) {
        this.id = id;
    }

    /** called by internal mechanisms, do not call yourself. */
    public CardReceipt(Long id, Long creditCardId, Long storeId, Double value, String currency, Long transaction, java.util.Date authorizationDate) {
    	this(id);
    	this.creditCardId = creditCardId;
    	this.storeId = storeId;
    	this.value = value;
    	this.currency = currency;
    	this.authorizationDate = authorizationDate;
    	this.transaction = transaction;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getCardReceiptDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
	if (id == null) throw new IllegalArgumentException("Property id cannot be null");
        this.id = id;
    }

    public long getCreditCardId() {
        return creditCardId;
    }

    public long getStoreId() {
        return storeId;
    }

    public double getValue() {
        return value;
    }


    public long getTransaction() {
        return transaction;
    }

    /** Not-null value. */
    public java.util.Date getAuthorizationDate() {
        return authorizationDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAuthorizationDate(java.util.Date authorizationDate) {
	if (authorizationDate == null) throw new IllegalArgumentException("Property authorizationDate cannot be null");
        this.authorizationDate = authorizationDate;
    }

    /** To-one relationship, resolved on first access. */
    public CreditCard getCreditCard() {
        long __key = this.creditCardId;
        if (creditCard__resolvedKey == null || !creditCard__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            CreditCardDao targetDao = daoSession.getCreditCardDao();
            CreditCard creditCardNew = targetDao.load(__key);
            synchronized (this) {
                creditCard = creditCardNew;
            	creditCard__resolvedKey = __key;
            }
        }
        return creditCard;
    }

    public void setCreditCard(CreditCard creditCard) {
        if (creditCard == null) {
            throw new DaoException("To-one property 'creditCardId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.creditCard = creditCard;
            creditCardId = creditCard.getId();
            creditCard__resolvedKey = creditCardId;
        }
    }

    /** To-one relationship, resolved on first access. */
    public Store getStore() {
        long __key = this.storeId;
        if (store__resolvedKey == null || !store__resolvedKey.equals(__key)) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            StoreDao targetDao = daoSession.getStoreDao();
            Store storeNew = targetDao.load(__key);
            synchronized (this) {
                store = storeNew;
            	store__resolvedKey = __key;
            }
        }
        return store;
    }

    public void setStore(Store store) {
        if (store == null) {
            throw new DaoException("To-one property 'storeId' has not-null constraint; cannot set to-one to null");
        }
        synchronized (this) {
            this.store = store;
            storeId = store.getId();
            store__resolvedKey = storeId;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here

    public CardReceipt(CreditCard cc, Store s, BigDecimal valor,
			Currency moeda, Calendar dataHoraAutorizacao, long autenticacao) {
		setCreditCard(cc);
		setStore(s);
		setTransaction(autenticacao);
		setValue(valor != null ? valor.doubleValue() : 0);
		if (moeda != null) setCurrency(moeda);
		setAuthorizationDate(dataHoraAutorizacao != null ? dataHoraAutorizacao.getTime() : null);
	}

    public void setValue(double value) {
    	if (Double.compare(value, 0d) == 0) throw new IllegalArgumentException("Property value cannot be zero");
        this.value = value;
    }

    /** Not-null value. */
    public Currency getCurrency() {
    	if (currency != null)
    		return Currency.getInstance(currency);
    	else
    		return Currency.getInstance(Locale.getDefault());
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCurrency(Currency currency) {
    	if (currency == null) throw new IllegalArgumentException("Property currency cannot be null");
        this.currency = currency.getCurrencyCode();
    }

    public void setTransaction(long transaction) {
    	if (transaction == 0) throw new IllegalArgumentException("Property transaction cannot be zero");
        this.transaction = transaction;
    }
    
    public void setCreditCardId(long creditCardId) {
    	if (creditCardId == 0) throw new IllegalArgumentException("Property creditCardId cannot be zero");
        this.creditCardId = creditCardId;
    }
    
    public void setStoreId(long storeId) {
    	if (storeId == 0) throw new IllegalArgumentException("Property storeId cannot be zero");
        this.storeId = storeId;
    }
    
    @Override
	public String toString() {
    	NumberFormat.getCurrencyInstance().setCurrency(getCurrency());
		return getCreditCard().toString() + " creditado " +
			NumberFormat.getCurrencyInstance().format(getValue()) + 
			" em " + getStore().toString();
	}
    
    public static class CardReceiptComparator implements Comparator<CardReceipt> {

		public int compare(CardReceipt arg0, CardReceipt arg1) {
			int sameCards = arg0.getCreditCard().getFinalNumbers() - arg1.getCreditCard().getFinalNumbers();
			if (sameCards == 0) {
				int sameStore = arg0.getStore().getOriginalName().compareTo(arg1.getStore().getOriginalName());
				if (sameStore == 0) {
					return (int) (arg0.getTransaction() - arg1.getTransaction());
				} else {
					return sameStore;
				}
			} else {
				return sameCards;
			}
		}
    	
    }
    // KEEP METHODS END

}
