package br.com.alepmendonca.creditcardusage.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import br.com.alepmendonca.creditcardusage.model.CreditCard;

import br.com.alepmendonca.creditcardusage.model.CardExtract;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CARD_EXTRACT.
*/
public class CardExtractDao extends AbstractDao<CardExtract, Long> {

    public static final String TABLENAME = "CARD_EXTRACT";

    /**
     * Properties of entity CardExtract.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CreditCardId = new Property(1, long.class, "creditCardId", false, "CREDIT_CARD_ID");
        public final static Property ExtractMonth = new Property(2, java.util.Date.class, "ExtractMonth", false, "EXTRACT_MONTH");
    };

    private DaoSession daoSession;


    public CardExtractDao(DaoConfig config) {
        super(config);
    }
    
    public CardExtractDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CARD_EXTRACT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'CREDIT_CARD_ID' INTEGER NOT NULL ," + // 1: creditCardId
                "'EXTRACT_MONTH' INTEGER NOT NULL );"); // 2: ExtractMonth
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CARD_EXTRACT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CardExtract entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getCreditCardId());
        stmt.bindLong(3, entity.getExtractMonth().getTime());
    }

    @Override
    protected void attachEntity(CardExtract entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CardExtract readEntity(Cursor cursor, int offset) {
        CardExtract entity = new CardExtract( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // creditCardId
            new java.util.Date(cursor.getLong(offset + 2)) // ExtractMonth
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CardExtract entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCreditCardId(cursor.getLong(offset + 1));
        entity.setExtractMonth(new java.util.Date(cursor.getLong(offset + 2)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(CardExtract entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(CardExtract entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCreditCardDao().getAllColumns());
            builder.append(" FROM CARD_EXTRACT T");
            builder.append(" LEFT JOIN CREDIT_CARD T0 ON T.'CREDIT_CARD_ID'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected CardExtract loadCurrentDeep(Cursor cursor, boolean lock) {
        CardExtract entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        CreditCard creditCard = loadCurrentOther(daoSession.getCreditCardDao(), cursor, offset);
         if(creditCard != null) {
            entity.setCreditCard(creditCard);
        }

        return entity;    
    }

    public CardExtract loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<CardExtract> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<CardExtract> list = new ArrayList<CardExtract>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<CardExtract> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<CardExtract> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
