package br.com.alepmendonca.creditcardusage.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import br.com.alepmendonca.creditcardusage.model.StoreType;
import br.com.alepmendonca.creditcardusage.model.Store;
import br.com.alepmendonca.creditcardusage.model.CreditCard;
import br.com.alepmendonca.creditcardusage.model.CardReceipt;
import br.com.alepmendonca.creditcardusage.model.CardExtract;
import br.com.alepmendonca.creditcardusage.model.CardExtractToReceipts;

import br.com.alepmendonca.creditcardusage.dao.StoreTypeDao;
import br.com.alepmendonca.creditcardusage.dao.StoreDao;
import br.com.alepmendonca.creditcardusage.dao.CreditCardDao;
import br.com.alepmendonca.creditcardusage.dao.CardReceiptDao;
import br.com.alepmendonca.creditcardusage.dao.CardExtractDao;
import br.com.alepmendonca.creditcardusage.dao.CardExtractToReceiptsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storeTypeDaoConfig;
    private final DaoConfig storeDaoConfig;
    private final DaoConfig creditCardDaoConfig;
    private final DaoConfig cardReceiptDaoConfig;
    private final DaoConfig cardExtractDaoConfig;
    private final DaoConfig cardExtractToReceiptsDaoConfig;

    private final StoreTypeDao storeTypeDao;
    private final StoreDao storeDao;
    private final CreditCardDao creditCardDao;
    private final CardReceiptDao cardReceiptDao;
    private final CardExtractDao cardExtractDao;
    private final CardExtractToReceiptsDao cardExtractToReceiptsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storeTypeDaoConfig = daoConfigMap.get(StoreTypeDao.class).clone();
        storeTypeDaoConfig.initIdentityScope(type);

        storeDaoConfig = daoConfigMap.get(StoreDao.class).clone();
        storeDaoConfig.initIdentityScope(type);

        creditCardDaoConfig = daoConfigMap.get(CreditCardDao.class).clone();
        creditCardDaoConfig.initIdentityScope(type);

        cardReceiptDaoConfig = daoConfigMap.get(CardReceiptDao.class).clone();
        cardReceiptDaoConfig.initIdentityScope(type);

        cardExtractDaoConfig = daoConfigMap.get(CardExtractDao.class).clone();
        cardExtractDaoConfig.initIdentityScope(type);

        cardExtractToReceiptsDaoConfig = daoConfigMap.get(CardExtractToReceiptsDao.class).clone();
        cardExtractToReceiptsDaoConfig.initIdentityScope(type);

        storeTypeDao = new StoreTypeDao(storeTypeDaoConfig, this);
        storeDao = new StoreDao(storeDaoConfig, this);
        creditCardDao = new CreditCardDao(creditCardDaoConfig, this);
        cardReceiptDao = new CardReceiptDao(cardReceiptDaoConfig, this);
        cardExtractDao = new CardExtractDao(cardExtractDaoConfig, this);
        cardExtractToReceiptsDao = new CardExtractToReceiptsDao(cardExtractToReceiptsDaoConfig, this);

        registerDao(StoreType.class, storeTypeDao);
        registerDao(Store.class, storeDao);
        registerDao(CreditCard.class, creditCardDao);
        registerDao(CardReceipt.class, cardReceiptDao);
        registerDao(CardExtract.class, cardExtractDao);
        registerDao(CardExtractToReceipts.class, cardExtractToReceiptsDao);
    }
    
    public void clear() {
        storeTypeDaoConfig.getIdentityScope().clear();
        storeDaoConfig.getIdentityScope().clear();
        creditCardDaoConfig.getIdentityScope().clear();
        cardReceiptDaoConfig.getIdentityScope().clear();
        cardExtractDaoConfig.getIdentityScope().clear();
        cardExtractToReceiptsDaoConfig.getIdentityScope().clear();
    }

    public StoreTypeDao getStoreTypeDao() {
        return storeTypeDao;
    }

    public StoreDao getStoreDao() {
        return storeDao;
    }

    public CreditCardDao getCreditCardDao() {
        return creditCardDao;
    }

    public CardReceiptDao getCardReceiptDao() {
        return cardReceiptDao;
    }

    public CardExtractDao getCardExtractDao() {
        return cardExtractDao;
    }

    public CardExtractToReceiptsDao getCardExtractToReceiptsDao() {
        return cardExtractToReceiptsDao;
    }

}
