package br.com.alepmendonca.creditcardusage;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CREDIT_CARD.
 */
public class CreditCard {

    private Long id;
    private int finalNumbers;
    private String issuer;
    private String owner;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CreditCard() {
    }

    public CreditCard(Long id) {
        this.id = id;
    }

    public CreditCard(Long id, int finalNumbers, String issuer, String owner) {
        this.id = id;
        this.finalNumbers = finalNumbers;
        this.issuer = issuer;
        this.owner = owner;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getFinalNumbers() {
        return finalNumbers;
    }

    public void setFinalNumbers(int finalNumbers) {
        this.finalNumbers = finalNumbers;
    }

    public String getIssuer() {
        return issuer;
    }

    public void setIssuer(String issuer) {
        this.issuer = issuer;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
